import { appendFileSync, mkdirSync, readFileSync } from "node:fs";
import { dirname } from "node:path";
import { AgentFirewall, FlightRecorder } from "./local-runtime.js";
import { databaseDecisionToRuleOakAction, filesystemDecisionToRuleOakAction } from "./local-guards.js";
export const OPENCLAW_STYLE_ADAPTER_VERSION = "1.0.0";
export const OPENCLAW_STYLE_ACTION_CATEGORIES = ["filesystem.read","filesystem.write","filesystem.delete","shell.run","database.query","database.mutate","database.drop","email.send","calendar.write","browser.automate","skill.install","secret.read","mcp.tool_call","context.retrieve"];
const ACTION_MAP = {"filesystem.delete":["filesystem","delete"],"filesystem.write":["filesystem","write"],"filesystem.read":["filesystem","read"],"database.query":["database","query"],"database.mutate":["database","mutate"],"database.drop":["database","destructive_ddl"],"system.run":["shell","run"],"shell.run":["shell","run"],"email.send":["email","send"],"calendar.write":["calendar","write"],"calendar.update":["calendar","write"],"browser.automate":["browser","automate"],"browser.purchase":["browser","purchase"],"skill.install":["skill","install"],"secret.read":["secret","read"],"secrets.read":["secret","read"],"mcp.tool_call":["mcp","tool_call"],"context.retrieve":["context","retrieve"]};
export function classifyOpenClawRisk(input = {}) { const text=JSON.stringify(input).toLowerCase(); const kind=String(input.kind || input.type || input.action || input.category || "unknown"); if(/rm\s+-rf|drop table|truncate|private key|secret|token|exfiltrate|ignore previous|bypass policy/.test(text)) return "critical"; if(/delete|write|mutate|update |insert |send|install|shell|tool_call|automate|purchase/.test(kind+text)) return "high"; return "low"; }
export function redactOpenClawAction(input = {}) { return JSON.parse(JSON.stringify(input, (k,v)=>/token|secret|password|api[_-]?key|authorization/i.test(k)?"[REDACTED]":v)); }
export function normalizeOpenClawAction(input = {}) { if(!input || typeof input !== "object") return { toolName:"unknown",operation:"unknown",target:null,risk:"high",input:{invalid:true},metadata:{adapter:"openclaw-style"}}; const kind=input.kind || input.type || input.action || input.tool || input.category || "unknown"; if(kind.startsWith("filesystem.")) return {...filesystemDecisionToRuleOakAction({ operation: kind.split(".")[1], path: input.path || input.target, input:redactOpenClawAction(input) }, input.policy || {}), risk: classifyOpenClawRisk(input), metadata:{adapter:"openclaw-style", sourceKind:kind}}; if(kind.startsWith("database.")) return {...databaseDecisionToRuleOakAction({ operation: kind.split(".")[1], sql: input.sql || input.query, input:redactOpenClawAction(input), database: input.database }, input.policy || {}), risk: classifyOpenClawRisk(input), metadata:{adapter:"openclaw-style", sourceKind:kind}}; const [toolName, operation] = ACTION_MAP[kind] || [String(kind).split(".")[0] || "unknown", String(kind).split(".")[1] || kind]; return { schemaVersion:"ruleoak.action_envelope.v1", toolName, operation, target: input.target || input.path || input.database || input.recipient || input.tool || null, risk: classifyOpenClawRisk(input), input:redactOpenClawAction(input), metadata:{adapter:"openclaw-style", sourceKind:kind} }; }
export function createOpenClawPolicy(overrides = {}) { return { defaultAction:"approval", allowedActions:["filesystem.read","context.retrieve","database.query",...(overrides.allowedActions||[])], approvalRequired:["email.send","calendar.write","filesystem.write","database.mutate","browser.automate","mcp.tool_call",...(overrides.approvalRequired||[])], blockedActions:["filesystem.delete","shell.run","browser.purchase","skill.install","secret.read","database.destructive_ddl",...(overrides.blockedActions||[])] }; }
export function loadOpenClawPolicy(pathOrPolicy = {}) { if(typeof pathOrPolicy === "string") return JSON.parse(readFileSync(pathOrPolicy,"utf8")); return Object.keys(pathOrPolicy||{}).length ? pathOrPolicy : createOpenClawPolicy(); }
function key(action){ return `${action.toolName}.${action.operation}`; }
export function evaluatePolicy(action = {}, policy = createOpenClawPolicy()) { const k=key(action); if((policy.blockedActions||[]).includes(k)) return {decision:"deny", action:k, reason:"blocked_by_policy"}; if((policy.approvalRequired||[]).includes(k)) return {decision:"needs_approval", action:k, reason:"approval_required"}; if((policy.allowedActions||[]).includes(k)) return {decision:"allow", action:k, reason:"allowed_by_policy"}; if(policy.defaultAction === "allow") return {decision:"allow", action:k, reason:"default_allow"}; if(policy.defaultAction === "deny") return {decision:"deny", action:k, reason:"default_deny"}; return action.risk === "low" ? {decision:"allow", action:k, reason:"low_risk"} : {decision:"needs_approval", action:k, reason:"default_approval"}; }
export function evaluateOpenClawAction(input = {}, policy = createOpenClawPolicy()) { const action=normalizeOpenClawAction(input); const decision=evaluatePolicy(action,policy); return { action, decision, evidence:[{type:"action_requested",action},{type:"policy_decision",decision}], version:OPENCLAW_STYLE_ADAPTER_VERSION }; }
export function createJsonlEvidenceSink(path){ mkdirSync(dirname(path),{recursive:true}); return { path, write(event){ appendFileSync(path, JSON.stringify(event)+"\n"); return event; } }; }
export function createMemoryEvidenceSink(){ const events=[]; return { write(e){ events.push(e); return e; }, list(){return [...events];} }; }
export function createApprovalCallback(mode="deny"){ return async request => ({ decision: mode === "allow" ? "allow" : "deny", reason:`approval_${mode}`, request }); }
export async function recordOpenClawAction(input = {}, executor = async () => ({ok:true}), policy = createOpenClawPolicy(), options = {}) { const action=normalizeOpenClawAction(input); let decision=evaluatePolicy(action,policy); const sink=options.evidenceSink || createMemoryEvidenceSink(); sink.write({type:"action_requested",action}); if(decision.decision === "needs_approval" && options.approvalCallback){ const approval=await options.approvalCallback({action,decision}); decision=approval.decision === "allow" ? {...decision, decision:"allow", approved:true} : {...decision, decision:"deny", approved:false, reason:approval.reason}; } sink.write({type:"policy_decision",decision,action}); if(decision.decision !== "allow") return { action, result:{executed:false,decision}, evidence:sink.list?.()||[], version:OPENCLAW_STYLE_ADAPTER_VERSION }; const output=await executor(input); sink.write({type:"action_executed", action, result:output}); return { action, result:{executed:true,decision,result:output}, evidence:sink.list?.()||[], version:OPENCLAW_STYLE_ADAPTER_VERSION }; }
export function createOpenClawRuleOakMiddleware({ policy = createOpenClawPolicy(), evidenceSink = createMemoryEvidenceSink(), approvalCallback = null } = {}) { return async function ruleoakOpenClawMiddleware(input, next = async () => ({ok:true})) { const r=await recordOpenClawAction(input, next, policy, { evidenceSink, approvalCallback }); return r.result; }; }
export function createOpenClawEvidenceSink(options={}) { return options.path ? createJsonlEvidenceSink(options.path) : new FlightRecorder({actor:options.actor||"openclaw-style-agent"}); }
export function replayEvidenceJsonl(text="") { return String(text).split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line)).map((event,index)=>({ index:index+1, type:event.type, decision:event.decision?.decision || event.payload?.decision || null })); }
export function adapterReadinessReport(){ return {version:OPENCLAW_STYLE_ADAPTER_VERSION, official:false, wording:"OpenClaw-style adapter", categories:OPENCLAW_STYLE_ACTION_CATEGORIES}; }
